// Common translations for fallback when database German content is missing
const commonTranslations: Record<string, Record<string, string>> = {
  en: {
    'Transform Your Life': 'Transform Your Life',
    'When teachers become Infinity Role Teachers, and every heart beats with love, the planet awakens—and so do we.': 'When teachers become Infinity Role Teachers, and every heart beats with love, the planet awakens—and so do we.',
    'Together, we give birth to a new era of conscious evolution.': 'Together, we give birth to a new era of conscious evolution.',
    'Switzerland': 'Switzerland',
    'Slovenia': 'Slovenia',
    'Our Mission': 'Our Mission',
    'Our Vision': 'Our Vision',
    'Discover what drives us forward': 'Discover what drives us forward',
    'Empower individuals on their journey to holistic wellness by providing transformative education, authentic healing practices, and a supportive global community guided by experienced role teachers.': 'Empower individuals on their journey to holistic wellness by providing transformative education, authentic healing practices, and a supportive global community guided by experienced role teachers.',
    'A world where everyone has access to ancient wisdom and modern practices necessary to achieve balance, health, and their unlimited potential.': 'A world where everyone has access to ancient wisdom and modern practices necessary to achieve balance, health, and their unlimited potential.',
    'Together, we birth a new era of conscious evolution.': 'Together, we birth a new era of conscious evolution.',
    'Embodied guide for inner orientation': 'Embodied guide for inner orientation',
    'Meditation': 'Meditation',
    'Holistic Healing': 'Holistic Healing',
    'Nutrition': 'Nutrition',
    'Special body exercises': 'Special body exercises',
    'Life Guidance': 'Life Guidance',
    'Bridging Traditional Wisdom and Modern Technology for Holistic Health': 'Bridging Traditional Wisdom and Modern Technology for Holistic Health',
    'Physician': 'Physician',
    'Educator': 'Educator',
    'Quantum Diagnostic': 'Quantum Diagnostic',
    'Teacher of awareness, pure love and spirituality': 'Teacher of awareness, pure love and spirituality',
    'Yoga & Meditation': 'Yoga & Meditation',
    'Wellness Coaching': 'Wellness Coaching',
    'Acupressure': 'Acupressure',
    'Reconnection Healing': 'Reconnection Healing',
    'Health is the harmony of body, mind, and spirit.': 'Health is the harmony of body, mind, and spirit.',
    'Nutrition as Aliveness': 'Nutrition as Aliveness',
    'Your body is an alchemical lab. Food is a bundle of memory and intelligence. That\'s life talking to life.': 'Your body is an alchemical lab. Food is a bundle of memory and intelligence. That\'s life talking to life.',
    'Yoga Exercises': 'Yoga Exercises',
    'Yoga helps you feel calmer, more flexible, and stronger. It eases stress and just makes your body feel way better.': 'Yoga helps you feel calmer, more flexible, and stronger. It eases stress and just makes your body feel way better.',
    'Sunyoga (= sun meditation)': 'Sunyoga (= sun meditation)',
    'It helps open your mind to spiritual awakening, fostering a deep connection with your inner self and one step closer to...': 'It helps open your mind to spiritual awakening, fostering a deep connection with your inner self and one step closer to...',
    'Aligns your body, mind, and energy, transforming joy from a chance event into your natural, constant state of being.': 'Aligns your body, mind, and energy, transforming joy from a chance event into your natural, constant state of being.',
    'Precision beats power, and timing beats speed': 'Precision beats power, and timing beats speed',
    '= strength + speed. It makes you faster, stronger in bursts, safer on your feet, burns more calories, keeps you feeling...': '= strength + speed. It makes you faster, stronger in bursts, safer on your feet, burns more calories, keeps you feeling...',
    'By stimulating these energy points, acupressure helps harmonize the flow of life force energy (Qi or Prana), empowering...': 'By stimulating these energy points, acupressure helps harmonize the flow of life force energy (Qi or Prana), empowering...',
    'Authenticity - Teaching methods rooted in ancient wisdom and validated by modern understanding.': 'Authenticity - Teaching methods rooted in ancient wisdom and validated by modern understanding.',
    'What our participants say': 'What our participants say',
    'Every individual lives in alignment with their soul\'s purpose, contributing to a thriving, conscious civilization.': 'Every individual lives in alignment with their soul\'s purpose, contributing to a thriving, conscious civilization.',
    'Designing Spaces for Healing': 'Designing Spaces for Healing',
    'Ritual and Rhythm in Modern Life': 'Ritual and Rhythm in Modern Life',
    'Your expert is your partner, celebrating victories and navigating challenges with you.': 'Your expert is your partner, celebrating victories and navigating challenges with you.',
    'We envision a future where holistic wellness practices are woven into the fabric of everyday life, where people don\'t just treat symptoms, but cultivate lasting vitality and inner peace.': 'We envision a future where holistic wellness practices are woven into the fabric of everyday life, where people don\'t just treat symptoms, but cultivate lasting vitality and inner peace.',
  },
  de: {
    'Transform Your Life': 'Transformieren Sie Ihr Leben',
    'When teachers become Infinity Role Teachers, and every heart beats with love, the planet awakens—and so do we.': 'Wenn Lehrer zu Infinity Role Teachers werden und jedes Herz mit Liebe schlägt, erwacht der Planet – und auch wir.',
    'Together, we give birth to a new era of conscious evolution.': 'Gemeinsam gebären wir eine neue Ära des bewussten Wandels.',
    'Switzerland': 'Schweiz',
    'Slovenia': 'Slowenien',
    'Our Mission': 'Unsere Mission',
    'Our Vision': 'Unsere Vision',
    'Discover what drives us forward': 'Entdecken Sie, was uns antreibt',
    'Empower individuals on their journey to holistic wellness by providing transformative education, authentic healing practices, and a supportive global community guided by experienced role teachers.': 'Individuen auf ihrer Reise zum ganzheitlichen Wohlbefinden zu stärken, indem wir transformative Bildung, authentische Heilpraktiken und eine unterstützende globale Gemeinschaft unter Anleitung erfahrener Rollenlehrer bieten.',
    'A world where everyone has access to ancient wisdom and modern practices necessary to achieve balance, health, and their unlimited potential.': 'Eine Welt, in der jeder Zugang zur alten Weisheit und modernen Praktiken hat, die notwendig sind, um Balance, Gesundheit und ihr unbegrenztes Potenzial zu erreichen.',
    'Together, we birth a new era of conscious evolution.': 'Gemeinsam gebären wir eine neue Ära des bewussten Wandels.',
    'Embodied guide for inner orientation': 'Verkörperter Führer für innere Orientierung',
    'Meditation': 'Meditation',
    'Holistic Healing': 'Ganzheitliche Heilung',
    'Nutrition': 'Ernährung',
    'Special body exercises': 'Spezielle Körperübungen',
    'Life Guidance': 'Lebensberatung',
    'Bridging Traditional Wisdom and Modern Technology for Holistic Health': 'Traditionelle Weisheit und moderne Technologie für ganzheitliche Gesundheit verbinden',
    'Physician': 'Arzt',
    'Educator': 'Pädagoge',
    'Quantum Diagnostic': 'Quantendiagnostik',
    'Teacher of awareness, pure love and spirituality': 'Lehrer des Bewusstseins, der reinen Liebe und Spiritualität',
    'Yoga & Meditation': 'Yoga & Meditation',
    'Wellness Coaching': 'Wellness-Coaching',
    'Acupressure': 'Akupressur',
    'Reconnection Healing': 'Reconnection-Heilung',
    'Health is the harmony of body, mind, and spirit.': 'Gesundheit ist die Harmonie von Körper, Geist und Seele.',
    'Nutrition as Aliveness': 'Ernährung als Lebendigkeit',
    'Your body is an alchemical lab. Food is a bundle of memory and intelligence. That\'s life talking to life.': 'Ihr Körper ist ein alchemistisches Labor. Nahrung ist ein Bündel aus Erinnerung und Intelligenz. Das ist Leben, das mit Leben spricht.',
    'Yoga Exercises': 'Yoga-Übungen',
    'Yoga helps you feel calmer, more flexible, and stronger. It eases stress and just makes your body feel way better.': 'Yoga hilft Ihnen, sich ruhiger, flexibler und stärker zu fühlen. Es lindert Stress und lässt Ihren Körper einfach besser fühlen.',
    'Sunyoga (= sun meditation)': 'Sunyoga (= Sonnenmeditation)',
    'It helps open your mind to spiritual awakening, fostering a deep connection with your inner self and one step closer to...': 'Es hilft, Ihren Geist für spirituelles Erwachen zu öffnen und fördert eine tiefe Verbindung zu Ihrem inneren Selbst und einen Schritt näher an...',
    'Aligns your body, mind, and energy, transforming joy from a chance event into your natural, constant state of being.': 'Richtet Ihren Körper, Geist und Energie aus und verwandelt Freude von einem zufälligen Ereignis in Ihren natürlichen, konstanten Zustand des Seins.',
    'Precision beats power, and timing beats speed': 'Präzision schlägt Kraft, und Timing schlägt Geschwindigkeit',
    '= strength + speed. It makes you faster, stronger in bursts, safer on your feet, burns more calories, keeps you feeling...': '= Stärke + Geschwindigkeit. Es macht Sie schneller, stärker in Schüben, sicherer auf den Füßen, verbrennt mehr Kalorien, hält Sie fühlen...',
    'By stimulating these energy points, acupressure helps harmonize the flow of life force energy (Qi or Prana), empowering...': 'Durch Stimulierung dieser Energiepunkte hilft die Akupressur, den Fluss der Lebensenergie (Qi oder Prana) zu harmonisieren und zu ermächtigen...',
    'Authenticity - Teaching methods rooted in ancient wisdom and validated by modern understanding.': 'Authentizität - Lehrmethoden, die in alter Weisheit verwurzelt und durch modernes Verständnis validiert sind.',
    'What our participants say': 'Was unsere Teilnehmer sagen',
    'Every individual lives in alignment with their soul\'s purpose, contributing to a thriving, conscious civilization.': 'Jeder Individuum lebt im Einklang mit dem Zweck seiner Seele und trägt zu einer blühenden, bewussten Zivilisation bei.',
    'Designing Spaces for Healing': 'Heilende Räume gestalten',
    'Ritual and Rhythm in Modern Life': 'Ritual und Rhythmus im modernen Leben',
    'Your expert is your partner, celebrating victories and navigating challenges with you.': 'Ihr Experte ist Ihr Partner, feiert Siege mit Ihnen und navigiert durch Herausforderungen.',
    'We envision a future where holistic wellness practices are woven into the fabric of everyday life, where people don\'t just treat symptoms, but cultivate lasting vitality and inner peace.': 'Wir unsen uns eine Zukunft, in der ganzheitliche Wellness-Praktiken in den Alltag gewoben sind, in der Menschen nicht nur Symptome behandeln, sondern anhaltende Vitalität und inneren Frieden kultivieren.',
  },
  fr: {
    'Transform Your Life': 'Transformez votre vie',
    'When teachers become Infinity Role Teachers, and every heart beats with love, the planet awakens—and so do we.': 'Lorsque les enseignants deviennent Infinity Role Teachers et que chaque cœur bat d\'amour, la planète s\'éveille — et nous aussi.',
    'Together, we give birth to a new era of conscious evolution.': 'Ensemble, nous donnons naissance à une nouvelle ère d\'évolution consciente.',
    'Switzerland': 'Suisse',
    'Slovenia': 'Slovénie',
    'Our Mission': 'Notre mission',
    'Our Vision': 'Notre vision',
    'Discover what drives us forward': 'Découvrez ce qui nous anime',
    'Empower individuals on their journey to holistic wellness by providing transformative education, authentic healing practices, and a supportive global community guided by experienced role teachers.': 'Autonomiser les individus dans leur voyage vers le bien-être holistique en fournissant une éducation transformatrice, des pratiques de guérison authentiques et une communauté mondiale de soutien guidée par des Enseignants de Rôle expérimentés.',
    'A world where everyone has access to ancient wisdom and modern practices necessary to achieve balance, health, and their unlimited potential.': 'Un monde où chacun a accès à la sagesse ancienne et aux pratiques modernes nécessaires pour atteindre l\'équilibre, la santé et leur potentiel infini.',
    'Together, we birth a new era of conscious evolution.': 'Ensemble, nous donnons naissance à une nouvelle ère d\'évolution consciente.',
    'Embodied guide for inner orientation': 'Guide incarné pour l\'orientation intérieure',
    'Meditation': 'Méditation',
    'Holistic Healing': 'Guérison holistique',
    'Nutrition': 'Nutrition',
    'Special body exercises': 'Exercices corporels spéciaux',
    'Life Guidance': 'Guidance de vie',
    'Bridging Traditional Wisdom and Modern Technology for Holistic Health': 'Pont entre la sagesse traditionnelle et la technologie moderne pour la santé holistique',
    'Physician': 'Médecin',
    'Educator': 'Éducateur',
    'Quantum Diagnostic': 'Diagnostic quantique',
    'Teacher of awareness, pure love and spirituality': 'Enseignant de la conscience, de l\'amour pur et de la spiritualité',
    'Yoga & Meditation': 'Yoga & Méditation',
    'Wellness Coaching': 'Coaching bien-être',
    'Acupressure': 'Acupressure',
    'Reconnection Healing': 'Guérison Reconnection',
    'Health is the harmony of body, mind, and spirit.': 'La santé est l\'harmonie du corps, de l\'esprit et de l\'âme.',
    'Nutrition as Aliveness': 'Nutrition comme vitalité',
    'Your body is an alchemical lab. Food is a bundle of memory and intelligence. That\'s life talking to life.': 'Votre corps est un laboratoire alchimique. La nourriture est un faisceau de mémoire et d\'intelligence. C\'est la vie qui parle à la vie.',
    'Yoga Exercises': 'Exercices de yoga',
    'Yoga helps you feel calmer, more flexible, and stronger. It eases stress and just makes your body feel way better.': 'Le yoga vous aide à vous sentir plus calme, plus flexible et plus fort. Il réduit le stress et fait simplement sentir votre corps bien mieux.',
    'Sunyoga (= sun meditation)': 'Sunyoga (= méditation solaire)',
    'It helps open your mind to spiritual awakening, fostering a deep connection with your inner self and one step closer to...': 'Cela aide à ouvrir votre esprit à l\'éveil spirituel, en favorisant une connexion profonde avec votre moi intérieur et un pas de plus vers...',
    'Aligns your body, mind, and energy, transforming joy from a chance event into your natural, constant state of being.': 'Aligne votre corps, votre esprit et votre énergie, transformant la joie d\'un événement fortuit en votre état naturel et constant d\'être.',
    'Precision beats power, and timing beats speed': 'La précision bat la puissance, et le timing bat la vitesse',
    '= strength + speed. It makes you faster, stronger in bursts, safer on your feet, burns more calories, keeps you feeling...': '= force + vitesse. Cela vous rend plus rapide, plus fort par accès, plus sûr sur vos pieds, brûle plus de calories, vous garde en forme...',
    'By stimulating these energy points, acupressure helps harmonize the flow of life force energy (Qi or Prana), empowering...': 'En stimulant ces points d\'énergie, l\'acupressure aide à harmoniser le flux d\'énergie vitale (Qi ou Prana), en renforçant...',
    'Authenticity - Teaching methods rooted in ancient wisdom and validated by modern understanding.': 'Authenticité - Méthodes d\'enseignement ancrées dans la sagesse ancienne et validées par la compréhension moderne.',
    'What our participants say': 'Ce que disent nos participants',
    'Every individual lives in alignment with their soul\'s purpose, contributing to a thriving, conscious civilization.': 'Chaque individu vit en alignement avec le but de son âme, contribuant à une civilisation prospère et consciente.',
    'Designing Spaces for Healing': 'Concevoir des espaces de guérison',
    'Ritual and Rhythm in Modern Life': 'Rituel et rythme dans la vie moderne',
    'Your expert is your partner, celebrating victories and navigating challenges with you.': 'Votre expert est votre partenaire, célébrant les victoires et naviguant les défis avec vous.',
    'We envision a future where holistic wellness practices are woven into the fabric of everyday life, where people don\'t just treat symptoms, but cultivate lasting vitality and inner peace.': 'Nous envisageons un avenir où les pratiques de bien-être holistique sont tissées dans le tissu de la vie quotidienne, où les gens ne traitent pas seulement les symptômes, mais cultivent une vitalité durable et une paix intérieure.',
  },
  si: {
    'Transform Your Life': 'Spremenite svoje življenje',
    'When teachers become Infinity Role Teachers, and every heart beats with love, the planet awakens—and so do we.': 'Ko učitelji postanejo Infinity Role Teachers in vsako srce bije z ljubeznijo, se planet prebudi — in tudi mi.',
    'Together, we give birth to a new era of conscious evolution.': 'Skupaj rodimo novo dobo zavestne evolucije.',
    'Switzerland': 'Švica',
    'Slovenia': 'Slovenija',
    'Our Mission': 'Naše poslanstvo',
    'Our Vision': 'Naša vizija',
    'Discover what drives us forward': 'Odkrijte, kaj nas vodi',
    'Empower individuals on their journey to holistic wellness by providing transformative education, authentic healing practices, and a supportive global community guided by experienced role teachers.': 'Posameznike na njihovi poti do celovitega dobrega počutja opremiti s preoblikovalno izobraževanjo, avtentičnimi zdravilnimi praksami in podporno globalno skupnostjo pod vodstvom izkušenih učiteljev vlog.',
    'A world where everyone has access to ancient wisdom and modern practices necessary to achieve balance, health, and their unlimited potential.': 'Svet, v katerem vsakdo ima dostop do stare modrosti in modernih praks, potrebnih za doseganje ravnotežja, zdravja in njihovega neskončnega potenciala.',
    'Together, we birth a new era of conscious evolution.': 'Skupaj rodimo novo dobo zavestne evolucije.',
    'Embodied guide for inner orientation': 'Udejanjeni vodnik za notranjo orientacijo',
    'Meditation': 'Meditacija',
    'Holistic Healing': 'Celostno zdravljenje',
    'Nutrition': 'Prehrana',
    'Special body exercises': 'Posebne telesne vaje',
    'Life Guidance': 'Življenjsko vodenje',
    'Bridging Traditional Wisdom and Modern Technology for Holistic Health': 'Povezovanje tradicionalne modrosti in moderne tehnologije za celostno zdravje',
    'Physician': 'Zdravnik',
    'Educator': 'Izobraževalec',
    'Quantum Diagnostic': 'Kvantna diagnostika',
    'Teacher of awareness, pure love and spirituality': 'Učitelj zavesti, čiste ljubezni in duhovnosti',
    'Yoga & Meditation': 'Joga & Meditacija',
    'Wellness Coaching': 'Wellness coaching',
    'Acupressure': 'Akupresura',
    'Reconnection Healing': 'Reconnection zdravljenje',
    'Health is the harmony of body, mind, and spirit.': 'Zdravje je harmonija telesa, uma in duha.',
    'Nutrition as Aliveness': 'Prehrana kot živost',
    'Your body is an alchemical lab. Food is a bundle of memory and intelligence. That\'s life talking to life.': 'Vaše telo je alkimistični laboratorij. Hrana je sveženj spomina in inteligence. To je življenje, ki govori življenju.',
    'Yoga Exercises': 'Joga vaje',
    'Yoga helps you feel calmer, more flexible, and stronger. It eases stress and just makes your body feel way better.': 'Joga vam pomaga, da se počutite mirnejše, bolj gibljive in močnejše. Zmanjšuje stres in vaše telo preprosto počuti veliko bolje.',
    'Sunyoga (= sun meditation)': 'Sunyoga (= sončna meditacija)',
    'It helps open your mind to spiritual awakening, fostering a deep connection with your inner self and one step closer to...': 'Pomaga odpreti vaš um za duhovno prebujenje, spodbuja globoko povezavo z vašim notranjim jazom in korak bližje k...',
    'Aligns your body, mind, and energy, transforming joy from a chance event into your natural, constant state of being.': 'Usmerja vaše telo, um in energijo, ter spreminja veselje iz naključnega dogodka v vaše naravno, stalno stanje bivanja.',
    'Precision beats power, and timing beats speed': 'Natančnost premaga moč, časovanje pa hitrost',
    '= strength + speed. It makes you faster, stronger in bursts, safer on your feet, burns more calories, keeps you feeling...': '= moč + hitrost. Naredi vas hitrejše, močnejše v sunkih, varnejše na nogah, kuri več kalorij, vas ohranja v formi...',
    'By stimulating these energy points, acupressure helps harmonize the flow of life force energy (Qi or Prana), empowering...': 'S spodbujanjem teh energetskih točk akupresura pomaga uskladiti pretok življenjske energije (Qi ali Prana), in krepi...',
    'Authenticity - Teaching methods rooted in ancient wisdom and validated by modern understanding.': 'Avtentičnost - Metode poučevanja, korenjene v stari modrosti in potrjene z modernim razumevanjem.',
    'What our participants say': 'Kaj pravijo naši udeleženci',
    'Every individual lives in alignment with their soul\'s purpose, contributing to a thriving, conscious civilization.': 'Vsak posameznik živi v skladu z namenom svoje duše in prispeva k uspešni, zavestni civilizaciji.',
    'Designing Spaces for Healing': 'Oblikovanje prostorov za zdravljenje',
    'Ritual and Rhythm in Modern Life': 'Ritual in ritem v modernem življenju',
    'Your expert is your partner, celebrating victories and navigating challenges with you.': 'Vaš strokovnjak je vaš partner, ki praznuje zmage in se sooča z izzivi z vami.',
    'We envision a future where holistic wellness practices are woven into the fabric of everyday life, where people don\'t just treat symptoms, but cultivate lasting vitality and inner peace.': 'Predstavljamo si prihodnost, v kateri so celostne prakse dobrega počutja tkane v vsakdanje življenje, kjer ljudje ne zdravijo samo simptomov, temveč gojijo trajno vitalnost in notranji mir.',
  }
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getLocalizedField<T = string>(
  item: any,
  field: string,
  locale: string,
  fallbackLocale: string = 'en'
): T {
  const localizedValue = item[`${field}_${locale}`];
  if (localizedValue !== null && localizedValue !== undefined && localizedValue !== '') {
    return localizedValue as T;
  }
  const fallbackValue = item[`${field}_${fallbackLocale}`];
  
  // If content is missing in database for current locale, try to translate common English phrases
  if ((locale === 'de' || locale === 'fr' || locale === 'si') && fallbackValue && typeof fallbackValue === 'string') {
    const translated = commonTranslations[locale]?.[fallbackValue];
    if (translated) {
      return translated as T;
    }
  }
  
  return fallbackValue as T;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function localizeItems<T extends Record<string, any>>(
  items: T[],
  fields: string[],
  locale: string
): (T & { localized: Record<string, unknown> })[] {
  return items.map((item) => ({
    ...item,
    localized: fields.reduce(
      (acc, field) => ({
        ...acc,
        [field]: getLocalizedField(item, field, locale),
      }),
      {}
    ),
  }));
}
